### ISSUE TITLE
Road labels are rendered below roads

### ISSUE THREAD

**Issue by knutole** [mapnik/node-mapnik#377]
I'm rendering a `vtile.render()` from OSM data, but the roads appear above the road labels. I've tried moving around the `CartoCSS` rules, but the labels are still below the roads. How can I fix this? Is it actually a matter of `css` rules, or does it have to do with something else? Thanks

![screen shot 2015-01-29 at 13 28 51](https://cloud.githubusercontent.com/assets/2197944/5957521/ddb1bdd8-a7ba-11e4-836b-9c8a5825d1d9.png)

**Comment by yohanboniface** [comment]
@knutole this thread may give some useful hints about this point:

https://github.com/mapzen/vector-datasource/issues/84#issuecomment-70907539

**Comment by knutole** [comment]
@yohanboniface Thanks for your feedback. According to @springmeyer in that post, it's supposed to be possible to use a `CartoCSS` attachment to render the label separately from the layer. However, I can't get it to work. See the `css` below, and attached screenshot. No matter how I twist and turn the `layers` and `attachments`, the labels still appear below the road. 

In the example below, there are two `::layers` with labels - different colors - and both appear below the road. Is my css syntax wrong? 

![screen shot 2015-01-29 at 14 07 05](https://cloud.githubusercontent.com/assets/2197944/5957977/2fe10334-a7c0-11e4-9bfc-4a3f50c04f20.png)
```css

#roads{

    ::labels {
    	line-color: white;
		line-width: 5;
    }
  
  	::labels_one {
       text-name: [name];
       text-face-name: @sans_bd;
       text-wrap-width: 100;
       text-wrap-before: true;
       text-fill: #f9294e;
       text-halo-fill: fadeout(#fff,80%);
       text-halo-radius: 2;
       text-halo-rasterizer: fast;
       text-line-spacing: -4;
       text-character-spacing: 0.5;
       text-size: 10;
       text-placement: line;
       text-avoid-edges: true;
       text-min-padding: 10;
       text-min-distance: 100;
    }
 
}



#roads{
  
  	::labels_two {
       text-name: [name];
       text-face-name: @sans_bd;

    }

}

```

**Comment by yohanboniface** [comment]
@knutole you need to take control on the layers order at this point I think (layer order is stronger than style order), see this example https://github.com/yohanboniface/thank-you-map/blob/master/project.yml#L23-L25

**Comment by knutole** [comment]
Ah, so I do need to create separate layers for `roads` and `roads_labels` after all? I understood from the discussion that it was not necessary? It certainly seems you're right though.

**Comment by yohanboniface** [comment]
You can use twice the same layer, using the "class" trick, like in the example, but then it depends how you are building your CartoCSS. Mapbox Studio does support this syntax (and Kosmtik too). If you do it by hand, you just need to pass twice the same layer, but with a distinct `class` key.

**Comment by knutole** [comment]
Thanks a lot for your feedback. Got it to work, there was some clutter in the .xml file. For reference, this is the valid css that yields labels on top of lines:

```css
#roads {
    ::labels {
    	line-color: white;
		line-width: 5;
    }
  	::labels_one {
       text-name: [name];
       text-face-name: @sans_bd;
       text-wrap-width: 100;
       text-wrap-before: true;
       text-fill: #ff002e;
       text-halo-fill: fadeout(#fff,80%);
       text-halo-radius: 2;
       text-halo-rasterizer: fast;
       text-line-spacing: -4;
       text-character-spacing: 0.5;
       text-size: 10;
       text-placement: line;
       text-avoid-edges: true;
       text-min-padding: 10;
       text-min-distance: 100;
    }
}
```
![screen shot 2015-01-29 at 15 07 56](https://cloud.githubusercontent.com/assets/2197944/5958781/a90e64d8-a7c8-11e4-9a02-57abd8f62814.png)

Thanks again!
